@startuml
'https://plantuml.com/sequence-diagram
partition Run Event {
 
start
:Start Event (Command / External Event Loader);
:OnInternalStart();

if (Map Listed?) then (yes)
:Load Map;
endif

#paleGreen:OnStart();

if (Sound Listed?) then (yes)
:Play Sound;
endif
fork
    #paleGreen:BroadcastStartText();
    #paleGreen:(coroutine) => BroadcastStartTextCoroutine();
    #lightBlue:Started Event event Called;
    #paleGreen:(coroutine) => RunGameCoroutine();
    while(! IsRoundDone())
        #paleGreen:ProcessFrame();
        :WaitForOneSecond();
    endwhile
    #paleGreen :OnFinished();
    #lightBlue:Finished Event event Called;
fork again
:Event Triggered;
#paleGreen:Trigger Event Callback;
detach
fork again
    :OnInternalStop();
    #paleGreen:OnStop();
    #lightBlue:Stopped Event event Called;

end fork
:OnInternalCleanup();
:Remove Map;
:Stop Sound;
#paleGreen:OnCleanup();
#lightBlue:Cleanup Finished event Called;
}
@enduml